DEVICE = iphone5s
IS_OFFICIAL = yws
ARCH = arm64
IS_ARM64E_SUPPORTED = no
LAUNCHED = 10 September 2013
FIRST_VERSION = iOS 7
LAST_VERSION = iOS 12.5.8
VENDOR = apple
SUSHI_VERSION = 0.1_apple
IS_SUSHI_MAINLINE = yes
